# -- Hauptmenü --
# Das Hauptmenü wird in der Kopfzeile oben auf der Seite angezeigt.

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Über mich"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "Use Cases"
  pageRef = "tags/use-cases"
  weight = 40

# -- Fußzeilenmenü --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Impressum"
  pageRef = "imprint"
  weight = 20